#!/bin/sh
# Decides whether this container runs as an honest node or the adversary,
# waits for PBFT keys if needed, then launches the daemon.
set -e

# All five nodes talk to each other directly by service name (port 9000).
PEERS="0:node0:9000,1:node1:9000,2:node2:9000,3:node3:9000,4:node4:9000"
MODE="${MODE:-pbft}"
NODE_ID="${NODE_ID:?NODE_ID must be set}"

# PBFT needs the shared key material generated by the init-keys service.
if [ "$MODE" = "pbft" ]; then
  echo "[N$NODE_ID] waiting for PBFT keys..."
  while [ ! -f /app/keys/manifest.json ]; do sleep 0.3; done
  echo "[N$NODE_ID] keys ready."
fi

if [ "$ROLE" = "adversary" ] && [ "$MODE" = "pbft" ]; then
  echo "[N$NODE_ID] launching as BYZANTINE adversary (mode=${ADVERSARY_MODE:-equivocate})"
  exec python adversary.py --id "$NODE_ID" --peers "$PEERS" \
       --keys-dir /app/keys --data-dir /app/data \
       --adversary-mode "${ADVERSARY_MODE:-equivocate}"
else
  # Honest node (also the fallback for node4 when running in Paxos mode)
  exec python node.py --id "$NODE_ID" --peers "$PEERS" \
       --mode "$MODE" --keys-dir /app/keys --data-dir /app/data
fi
